AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sample vpc
Parameters:
  S3BucketPrefix:
    Description: bucket for CodeBuild build image
    Type: String
    # Default: yagita

Resources:
  # -----------------------------------------
  # S3 Bucket for Build Image
  # -----------------------------------------
  BuildImageS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketPrefix}-for-codedeploy-${AWS::Region}


# -----------------------------------------
# Output
# -----------------------------------------
Outputs:
  BuildImageS3Bucket:
    Description: BuildImageS3Bucket
    Value: !Ref BuildImageS3Bucket
    Export:
      Name: !Sub ${S3BucketPrefix}-for-codedeploy-${AWS::Region}
